config/routes.rb
Rails.application.routes.draw do
  resources :postulations do
    get '/control_interno' => "postulations#control", on: :member
    get '/download_files' => "postulations#download_files", on: :member
    get '/data_dump' => "postulations#data_dump", on: :collection
  end
  resources :info_requests
  devise_for :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  as :postulations do
    get "/postular" => "postulations#new"
  end
  
  
  as :info_request do
    get "/solicitar_informacion" => "info_requests#new"
  end
  
  root "landings#index"

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
#  before_action :set_landing, only: [:show, :edit, :update, :destroy]

  # GET /landings
  # GET /landings.json
  def index
    
  end

end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/_form.html.erb
<%= simple_form_for(@landing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/landings/edit.html.erb
<h1>Editing Landing</h1>

<%= render 'form' %>

<%= link_to 'Show', @landing %> |
<%= link_to 'Back', landings_path %>

app/views/landings/index.html.erb
<div class='col-md-8 col-md-offset-2 texto-landing'>
  <div class='col-md-12'>Bienvenido al sistema de Postulación en Línea de la Escuela de Postgrado de la Facultad de Artes de la Universidad de Chile.</div>
  <div class='spacer25'>&nbsp;</div>
  <div class='col-md-12'>Previo a ingresar su postulación al programa seleccionado, asegúrese de haber leído el instructivo del programa y comprobar si dispone de todos los documentos solicitados.</div>
  <div class='spacer25'>&nbsp;</div>
  <div class='col-md-12'>Cualquier consulta, por favor dirigirse a la Secretaría de Postgrado del Programa.</div>
  <div class='spacer25'>&nbsp;</div>
  <div class='col-md-12'>Le saluda atentamente,</div>
  <div class='spacer25'>&nbsp;</div>
  <div class='col-md-12'>Escuela de Postgrado</div>
  <div class='col-md-12'>Facultad de Artes</div>
  <div class='col-md-12'>Universidad de Chile</div>
</div>

<div class='cuadro-descarga col-md-8 col-md-offset-2'>
  <div class='col-md-12'><h4>Descarga: </h4></div>
  <div class='col-md-12'><a href='/assets/IDPEL.pdf'>Instructivo de postulación en línea</a></div>
  <div class='col-md-12'><a href='/assets/REQUISITOS_ESPECIALES.pdf'>Requisitos Especiales</a></div>
  <div class='col-md-12'><a href='/assets/Ficha_postulacion_Postgrado_2016.xlsx'>Ficha de postulación Postgrado</a></div>
  <div class='col-md-12'><a href='/assets/Formulario_postulacion_Doctorado_2016.doc'>Formulario de postulación Doctorado</a></div>
  <div class='col-md-12'><a href='/assets/RES_N122_Valores_por_concepto_inscripcion_postulaciones_2016_ESCUELA_DE_POSTGRADO.pdf'>RES N°122 Valores por concepto inscripción postulaciones 2016 ESCUELA DE POSTGRADO</a></div>
</div>
<div class='botones-formularios-landing'>
    <div class='col-md-4 col-md-offset-2'>
      <a href="/solicitar_informacion" class='btn btn-azul btn-lg btn-block'>Solicitar información</a>
    </div>
  <div class='col-md-4'>
    <a href="/postular" class="btn btn-rosado btn-lg btn-block">Postular</a>  
  </div>
</div>

app/views/landings/new.html.erb
<h1>New Landing</h1>

<%= render 'form' %>

<%= link_to 'Back', landings_path %>

app/views/landings/show.html.erb
<%= link_to 'Edit', edit_landing_path(@landing) %> |
<%= link_to 'Back', landings_path %>