config/routes.rb
Rails.application.routes.draw do
  resources :postulations do
    get '/control_interno' => "postulations#control", on: :member
    get '/download_files' => "postulations#download_files", on: :member
    get '/data_dump' => "postulations#data_dump", on: :collection
  end
  resources :info_requests
  devise_for :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  as :postulations do
    get "/postular" => "postulations#new"
  end
  
  
  as :info_request do
    get "/solicitar_informacion" => "info_requests#new"
  end
  
  root "landings#index"

end

app/models/postulation.rb
class Postulation < ActiveRecord::Base
  belongs_to :program
  belongs_to :financing
  
  has_and_belongs_to_many :find_outs
  
  
  has_attached_file :cv
  has_attached_file :picture
  has_attached_file :degree_1
  has_attached_file :degree_2
  has_attached_file :postulation_tab
  has_attached_file :inscription_receip
  has_attached_file :intention_letter
  has_attached_file :ci
  has_attached_file :recommendation_letter_1
  has_attached_file :recommendation_letter_2
  has_attached_file :tesis_proposal
  has_attached_file :interest_declaration
  
  do_not_validate_attachment_file_type :cv
  do_not_validate_attachment_file_type :picture
  do_not_validate_attachment_file_type :degree_1
  do_not_validate_attachment_file_type :degree_2
  do_not_validate_attachment_file_type :postulation_tab
  do_not_validate_attachment_file_type :inscription_receip
  do_not_validate_attachment_file_type :intention_letter
  do_not_validate_attachment_file_type :ci
  do_not_validate_attachment_file_type :recommendation_letter_1
  do_not_validate_attachment_file_type :recommendation_letter_2
  do_not_validate_attachment_file_type :tesis_proposal
  do_not_validate_attachment_file_type :interest_declaration
  
  
  
end

app/controllers/postulations_controller.rb
class PostulationsController < ApplicationController
  before_action :set_postulation, only: [:show, :edit, :update, :destroy, :control]
  before_action :restrict_not_logged, only: [:index, :update, :destroy, :edit]
  require 'zip'
  
  # GET /postulations
  # GET /postulations.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: PostulationDatatable.new(view_context) }
    end
  end
  
  def download_files
    
    postulation = Postulation.find(params[:id])
    filename = "#{postulation.rut.gsub(".", "") if postulation.rut.present?}-Programa_#{postulation.program.try(:code)}-#{postulation.name}_#{postulation.surname}.zip"
    
    temp_file = Tempfile.new(filename)
    
    paths = []
    
    paths << [ postulation.cv.try(:path), postulation.cv_file_name ]
    paths << [ postulation.picture.try(:path), postulation.picture_file_name ]
    paths << [ postulation.degree_1.try(:path), postulation.degree_1_file_name ]
    paths << [ postulation.degree_2.try(:path), postulation.degree_2_file_name ]
    paths << [ postulation.postulation_tab.try(:path), postulation.postulation_tab_file_name ]
    paths << [ postulation.inscription_receip.try(:path), postulation.inscription_receip_file_name ]
    paths << [ postulation.intention_letter.try(:path), postulation.intention_letter_file_name ]
    paths << [ postulation.ci.try(:path), postulation.ci_file_name ]
    paths << [ postulation.recommendation_letter_1.try(:path), postulation.recommendation_letter_1_file_name ]
    paths << [ postulation.recommendation_letter_2.try(:path), postulation.recommendation_letter_2_file_name ]
    paths << [ postulation.tesis_proposal.try(:path), postulation.tesis_proposal_file_name ]
    paths << [ postulation.interest_declaration.try(:path), postulation.interest_declaration_file_name ]
    
  
    paths.map! {|p| p if p != [nil, nil] }
    paths = paths.compact.uniq { |p| p[1]}
  
  
  if paths != [[nil, nil]]
    Zip::File.open(temp_file.path, Zip::File::CREATE) do |zip|
      paths.each do |p|
        zip.add(p[1], p[0])
      end
    end

    zip_data = File.read(temp_file.path)
    send_data(zip_data, :type => 'application/zip', :filename => filename)
  else
    render html: "<div class='col-md-12'><h1 class='title1'>No hay archivos adjuntos!</h1></div>".html_safe, layout: true
  end
    

    

  end
  
  def data_dump
    estados = ['PENDIENTE', 'ACEPTADO', 'RECHAZADO']
    @postulaciones = []
    @solicitudes_informacion = []
    Postulation.all.each do |p|
      postulacion = [
        p.id,
        p.program.try(:code),
        p.program.try(:name),
        p.name,
        p.surname,
        p.second_surname,
        p.rut,
        (view_context.l(p.birthdate) if p.birthdate),
        p.birthplace,
        p.nationality,
        p.phone,
        p.mobile_phone,
        p.message_phone,
        p.email,
        p.address,
        p.commune,
        p.city,
        p.degree_school,
        p.degree,
        p.degree_country,
        p.degree_year,
        p.other_degree,
        p.other_degree_country,
        p.other_degree_year,
        p.occupation,
        p.work_address,
        p.work_commune,
        p.work_city,
        p.work_phone,
        p.work_email,
        p.observations,
        p.find_outs.map { |fo| fo.name  }.join(' | '),
        p.financing.try(:name),
        p.folder_delivery,
        p.interview,
        estados[p.postulation_status],
        estados[p.enrollment_status],
        estados[p.tuition_status],
        p.intern_observations
      ]
      @postulaciones << postulacion
    end
    
    
    InfoRequest.all.each do |ir|
      info_request = [
        ir.id,
        ir.program.try(:code),
        ir.program.try(:name),
        ir.name,
        ir.surname,
        ir.second_surname,
        ir.rut,
        ir.email,
        ir.observations,
        ir.find_outs.map { |fo| fo.name  }.join(' | ')
      ]
      @solicitudes_informacion << info_request
    end
    
    require 'json'
    
    @postulaciones = @postulaciones.to_json
    @solicitudes_informacion = @solicitudes_informacion.to_json
    
  end
  
  def control
    
    @postulation = Postulation.find(params[:id])
    if params[:postulation]
      @postulation.update(postulation_params)
    end
    
    
#    render json: params[:id]
  end

  # GET /postulations/1
  # GET /postulations/1.json
  def show
    render "recieved" if !current_user
  end

  # GET /postulations/new
  def new
    @postulation = Postulation.new
    
  end

  # GET /postulations/1/edit
  def edit
  end

  # POST /postulations
  # POST /postulations.json
  def create
    @postulation = Postulation.new(postulation_params)
    @postulation.postulation_status = 0
    @postulation.enrollment_status = 0
    @postulation.tuition_status = 0
    
    formulario_valido = postulation_params.map { |k, parm| parm.blank? ? 0 : 1 }.sum > 0
    
    respond_to do |format|
      if formulario_valido and @postulation.save
        format.html { redirect_to @postulation, notice: 'Postulation was successfully created.' }
        format.json { render :show, status: :created, location: @postulation }
      else
        format.html { render :new }
        format.json { render json: @postulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postulations/1
  # PATCH/PUT /postulations/1.json
  def update
    respond_to do |format|
      if @postulation.update(postulation_params)
        format.html { redirect_to @postulation, notice: 'Postulation was successfully updated.' }
        format.json { render :show, status: :ok, location: @postulation }
      else
        format.html { render :edit }
        format.json { render json: @postulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postulations/1
  # DELETE /postulations/1.json
  def destroy
    @postulation.destroy
    respond_to do |format|
      format.html { redirect_to postulations_url, notice: 'Postulation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def restrict_not_logged
      redirect_to root_path if !current_user
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_postulation
      @postulation = Postulation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postulation_params
      params.require(:postulation).permit(:program_id, :name, :internal_commentary, :surname, :second_surname, :rut, :birthdate, :birthplace, :nationality, :phone, :mobile_phone, :message_phone, :email, :address, :commune, :city, :degree_school, :degree, :degree_country, :degree_year, :other_degree, :other_degree_country, :other_degree_year, :occupation, :work_address, :work_commune, :work_city, :work_phone, :work_email, :observations, :financing_id, :cv, :picture, :degree_1, :degree_2, :postulation_tab, :inscription_receip, :intention_letter, :ci, :recommendation_letter_1, :recommendation_letter_2, :tesis_proposal, :interest_declaration, :folder_delivery, :interview, :postulation_status, :enrollment_status, :tuition_status, :intern_observations, :no_continuation, :find_out_other, find_out_ids: [] )
    end
end

app/helpers/postulations_helper.rb
module PostulationsHelper
end

app/views/postulations/_form.html.erb
<%= simple_form_for(@postulation) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-8 col-md-offset-2">
    <div class='step-panel' data-step=1>
      <div class='col-md-12 text-center'>
        <h4>Para comenzar seleccione el programa al que desea postular</h4>
      </div>
      <%= f.association :program, :collection => Program.where(:active => true), label: "Nombre del programa" %>
      <button class='pull-right btn btn-success next-step'>Siguiente</button>
    </div>
    <div class='step-panel' data-step=2>
      <%= f.input :rut, label: "Cédula de identidad o pasaporte" %>
      <%= f.input :name, label: "Nombres" %>
      <%= f.input :surname, label: "Apellido paterno" %>
      <%= f.input :second_surname, label: "Apellido materno" %>
      <%= f.input :birthdate, as: :date, start_year: Date.today.year - 5, end_year: Date.today.year - 100, label: "Fecha de nacimiento", :include_blank => true %>
<!--      <%= f.input :birthplace, label: "Lugar de nacimiento" %>-->
      <%= f.input :nationality, label: "Nacionalidad" %>
      <%= f.input :phone, label: "Fono de contacto" %>
      <%= f.input :mobile_phone, label: "Fono celular" %>
<!--      <%= f.input :message_phone, label: "Teléfono de mensajes" %>-->
      <%= f.input :email, label: "Correo electrónico" %>
      <%= f.input :address, label: "Domicilio" %>
      <%= f.input :commune, label: "Comuna" %>
      <%= f.input :city, label: "Ciudad" %>
      <button class='pull-left btn btn-danger last-step'>Anterior</button>
      <button class='pull-right btn btn-success next-step'>Siguiente</button>
    </div>
    <div class='step-panel' data-step=3>
      <%= f.input :degree, label: "Títulos profesionales y/o grados academicos" %>
      <%= f.input :degree_school, label: "Entidad educacional donde sus titulos profesionales o grados académicos" %>
      <%= f.input :degree_country, as: :string, label: "País donde obtuvo sus títulos profesionales o grados académicos" %>
      <%= f.input :degree_year, label: "Año de obtención del título profesional o grado académico" %>
<!--      <%= f.input :other_degree, label: "Otro título (si aplica)" %>-->
<!--      <%= f.input :other_degree_country, as: :string, label: "País" %>-->
<!--      <%= f.input :other_degree_year, label: "Año" %>-->
      <%= f.input :occupation, label: "Ocupación actual" %>
<!--      <%= f.input :work_address, label: "Domicilio laboral" %>-->
<!--      <%= f.input :work_commune, label: "Comuna" %>-->
<!--      <%= f.input :work_city, label: "Ciudad" %>-->
<!--      <%= f.input :work_phone, label: "Teléfono laboral" %>-->
<!--      <%= f.input :work_email, label: "Correo electronico" %>-->
      <button class='pull-left btn btn-danger last-step'>Anterior</button>
      <button class='pull-right btn btn-success next-step'>Siguiente</button>
    </div>
    <div class='step-panel' data-step=4>
      <%= f.association :find_outs, label: "¿Como se enteró del programa?", input_html: {multiple: true, class: 'chosen-select', 'data-placeholder': '¿Como te enteraste?, click aquí'} %>
      <%= f.input :find_out_other, label: "Especifique donde se enteró.", wrapper_html: { class: 'find_out_wrapper' } %>
      <%= f.association :financing, label: "Fuente de financiamiento de estudios" %>
      <%= f.input :no_continuation, :collection => [['Si', true], ['No', false]], as: :radio_buttons, label: "En caso que la beca no sea adjudicada ¿continúa con la postulación?", wrapper_html: { class: 'no_continuation_wrapper' } %>
      <%= f.input :observations, label: "Ingrese comentarios u observaciones (si amerita)" %>
      <button class='pull-left btn btn-danger last-step'>Anterior</button>
      <button class='pull-right btn btn-success next-step'>Siguiente</button>
    </div>
    <div class='step-panel' data-step=5>
      <%= f.input :cv, as: :file, label: "Currículum vitae (obligatorio)"  %>
      <%= f.input :picture, as: :file, label: "Fotografía digital de 3x4 cms" %>
      <%= f.input :degree_1, as: :file, label: "Título o grado académico"  %>
<!--      <%= f.input :degree_2, as: :file, label: "Título o grado académico 2"   %>-->
      <%= f.input :postulation_tab, as: :file, label: "Ficha de postulación firmada (obligatoria)"  %>
      <%= f.input :inscription_receip, as: :file, label: "Comprobante de pago de arancel de inscripción (obligatorio)"  %>
<!--      <%= f.input :intention_letter, as: :file, label: "Cédula de identidad o pasaporte digitalizado por ambos lados (obligatorio)"  %>-->
      <%= f.input :ci, as: :file, label: "Cédula de identidad o pasaporte digitalizado por ambos lados (obligatorio)"  %>
      <%= f.input :recommendation_letter_1, as: :file, label: "Carta de recomendación"  %>
<!--      <%= f.input :recommendation_letter_2, as: :file, label: "Carta de recomendación 2"  %>-->
      <%= f.input :tesis_proposal, as: :file, label: "Pre proyecto / anteproyecto / propuesta de trabajo de tesis" %>
      <%= f.input :interest_declaration, as: :file, label: "Declaración de intereses o de propósitos y objetivos que desea alcanzar a través del programa"  %>
      <button class='pull-left btn btn-danger last-step'>Anterior</button>
      <button class='pull-right btn btn-success next-step'>Siguiente</button>
    </div>
    <div class='step-panel' data-step=6>
      <div class='col-md-12 tabla-final'>
        <table class='table'>
          <thead>
            <th colspan=2 class='text-center'> Resumen postulación </th>
          </thead>
          <tbody>
            <tr>
              <th>Programa:</th>
              <td id='table_program'></td>
            </tr>
            <tr>
              <th>Cédula de identidad o pasaporte:</th>
              <td id='table_postulation_rut'></td>
            </tr>
            <tr>
              <th>Nombres:</th>
              <td id='table_postulation_name'></td>
            </tr>
            <tr>
              <th>Apellido paterno:</th>
              <td id='table_postulation_surname'></td>
            </tr>
            <tr>
              <th>Apellido materno:</th>
              <td id='table_postulation_second_surname'></td>
            </tr>
            <tr>
              <th>Nacionalidad:</th>
              <td id='table_postulation_nationality'></td>
            </tr>
            <tr>
              <th>Fono de contacto:</th>
              <td id='table_postulation_phone'></td>
            </tr>
            <tr>
              <th>Fono celular:</th>
              <td id='table_postulation_mobile_phone'></td>
            </tr>
            <tr>
              <th>Correo electronico:</th>
              <td id='table_postulation_email'></td>
            </tr>
            <tr>
              <th>Domicilio:</th>
              <td id='table_postulation_address'></td>
            </tr>
            <tr>
              <th>Comuna:</th>
              <td id='table_postulation_commune'></td>
            </tr>
            <tr>
              <th>Ciudad:</th>
              <td id='table_postulation_city'></td>
            </tr>
            <tr>
              <th>Títulos profesionales y/o grados académicos:</th>
              <td id='table_postulation_degree'></td>
            </tr>
            <tr>
              <th>Entidad educacional donde obtuvo<br />sus títulos profesionales <br /> o grados académicos:</th>
              <td id='table_postulation_degree_school'></td>
            </tr>
            <tr>
              <th>Año de obtención del título <br />profesional o grado académico:</th>
              <td id='table_postulation_degree_year'></td>
            </tr>
            <tr>
              <th>Ocupación actual:</th>
              <td id='table_postulation_occupation'></td>
            </tr>
            <tr>
              <th>Currículum vitae</th>
              <td id='table_postulation_cv'></td>
            </tr>
            <tr>
              <th>Fotografía digital de 3x4 cms</th>
              <td id='table_postulation_picture'></td>
            </tr>
            <tr>
              <th>Título o grado académico</th>
              <td id='table_postulation_degree_1'></td>
            </tr>
            <tr>
              <th>Ficha de postulación firmada</th>
              <td id='table_postulation_postulation_tab'></td>
            </tr>
            <tr>
              <th>Comprobante de pago de arancel de inscripción</th>
              <td id='table_postulation_inscription_receip'></td>
            </tr>
            <tr>
              <th>Cédula de identidad o pasaporte digitalizado por ambos lados</th>
              <td id='table_postulation_ci'></td>
            </tr>
            <tr>
              <th>Carta de recomendación</th>
              <td id='table_postulation_recommendation_letter_1'></td>
            </tr>
            <tr>
              <th>Pre proyecto / anteproyecto / propuesta de trabajo de tesis</th>
              <td id='table_postulation_tesis_proposal'></td>
            </tr>
            <tr>
              <th>Declaración de intereses o de propósitos y objetivos que desea alcanzar a través del programa</th>
              <td id='table_postulation_interest_declaration'></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class='col-md-12'>
        <%= f.button :submit, "Enviar postulación", class: 'btn btn-info col-md-6 col-md-offset-3' %>
      </div>
      <div class='spacer50'></div>
      <div class='spacer50'></div>
      <div class='spacer50'></div>
        <button class='pull-left btn btn-danger last-step'>Anterior</button>
    </div>
  </div>
  <div class="modal fade" id="modal-validation" tabindex="-1" role="dialog" aria-labelledby="modal-validation">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="exampleModalLabel">Error de validación</h4>
        </div>
        <div class="modal-body text-center">
          <h4>Los campos en rojo son obligatorios.</h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/postulations/edit.html.erb
<%= render 'form_internal_commentary' %>

<%= link_to 'Back', postulations_path %>

app/views/postulations/index.html.erb
<div class='col-md-12 col-sm-12'>
  <h1 class='titulo1'>Postulaciones</h1>
  <% if current_user %>
    <% if current_user.has_role? :admin %>
  <h3>EP: Estado postulación | EC: Entrega carpeta | FE: Fecha entrevista | EM: Estado matricula | EPA: Estado pago arancel | OI: Observación interna</h3>
    <% end %>
    <% if current_user.has_any_role? :admin, :descarga %>
  <a class='btn btn-success pull-right' href='/postulations/data_dump' style='color: white;'>Ver volcado de datos</a>
    <% end %>
  <table class='table table-bordered' id="postulations-table" data-source="<%= postulations_path(format: :json) %>">
    <thead>
      <tr>
        <% if current_user.has_any_role? :admin, :acceso %>
        <th>Programa</th>
        <% end %>
        <th>Nombre</th>
        <th>Email</th>
        <th>Rut</th>
        <% if current_user.has_any_role? :admin, :acceso %>
        <th>Comentarios</th>
        <th>Como se entero</th>
        <% end %>
        <% if current_user.has_role? :admin %>
          <th>EP</th>
          <th>EC</th>
          <th>FE</th>
          <th>EM</th>
          <th>EPA</th>
          <th>OI</th>
        <% end %>
        <% if current_user.has_role? :acceso %>
          <th>Ultima modificación</th>
        <% end %>
        <th>Opciones</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  <% end %>
</div>

app/views/postulations/new.html.erb
<div class='col-md-12 spacer50'>&nbsp;</div>
<div class='col-md-12'>
  <ol class="progtrckr" id='progreso' data-progtrckr-steps="6">
    <li class="progtrckr-todo" data-step=1>Programa</li>
    <li class="progtrckr-todo" data-step=2>Datos</li>
    <li class="progtrckr-todo" data-step=3>Formación</li>
    <li class="progtrckr-todo" data-step=4>Otros</li>
    <li class="progtrckr-todo" data-step=5>Documentos</li>
  </ol>
</div>

<div class='col-md-12 spacer50'>
<!--  <h1 class='titulo1'>Formulario de postulación</h1>-->
  &nbsp;
</div>
<br />
<%= render 'form' %>

<!--
<%= link_to 'Back', postulations_path %>
-->

app/views/postulations/show.html.erb
<div class='col-md-12'>
  <h4> Programa: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.program.try(:name) %>
</div>

<div class='col-md-12'>
  <h4> Nombre: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.name %>
</div>

<div class='col-md-12'>
  <h4> Apellido: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.surname %>
</div>
<div class='col-md-12'>
  <h4> Segundo apellido </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.second_surname %>
</div>
<div class='col-md-12'>
  <h4> Rut: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.rut %>
</div>
<div class='col-md-12'>
  <h4> Fecha de nacimiento: </h4>
</div>
<div class='col-md-12'>
  <%= l(@postulation.birthdate) if @postulation.birthdate %>
</div>
<div class='col-md-12'>
  <h4> Lugar de nacimiento: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.birthplace %>
</div>
<div class='col-md-12'>
  <h4> Nacionalidad: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.nationality %>
</div>
<div class='col-md-12'>
  <h4> Telefono: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.phone %>
</div>
<div class='col-md-12'>
  <h4> Telefono movil: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.mobile_phone %>
</div>
<div class='col-md-12'>
  <h4> Telefono para mensajes: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.message_phone %>
</div>
<div class='col-md-12'>
  <h4> Correo electronico: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.email %>
</div>
<div class='col-md-12'>
  <h4> Dirección: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.address %>
</div>
<div class='col-md-12'>
  <h4> Comuna: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.commune %>
</div>
<div class='col-md-12'>
  <h4> Ciudad: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.city %>
</div>
<div class='col-md-12'>
  <h4> Entidad educacional donde obtuvo su título anterior: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.degree_school %>
</div>
<div class='col-md-12'>
  <h4> Titulo o grado: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.degree %>
</div>
<div class='col-md-12'>
  <h4> País (título):</h4>
</div>
<div class='col-md-12'>
  <%= @postulation.degree_country %>
</div>
<div class='col-md-12'>
  <h4> Año de títulacion: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.degree_year %>
</div>
<div class='col-md-12'>
  <h4> Otro grado:</h4>
</div>
<div class='col-md-12'>
  <%= @postulation.other_degree %>
</div>
<div class='col-md-12'>
  <h4> País (otro grado):</h4>
</div>
<div class='col-md-12'>
  <%= @postulation.other_degree_country %>
</div>
<div class='col-md-12'>
  <h4> Año (otro grado): </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.other_degree_year %>
</div>
<div class='col-md-12'>
  <h4> Ocupación: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.occupation %>
</div>
<div class='col-md-12'>
  <h4> Domicilio laboral: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.work_address %>
</div>
<div class='col-md-12'>
  <h4> Comuna laboral: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.work_commune %>
</div>
<div class='col-md-12'>
  <h4> Ciudad laboral: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.work_city %>
</div>
<div class='col-md-12'>
  <h4> Telefono laboral: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.work_phone %>
</div>
<div class='col-md-12'>
  <h4> Correo electronico laboral: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.work_email %>
</div>
<div class='col-md-12'>
  <h4> Observaciones: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.observations %>
</div>
<div class='col-md-12'>
  <h4> Como se enteró del programa: </h4>
</div>
<div class='col-md-12'>
  <% @postulation.find_outs.map do |fo| %>
  <div class='col-md-12'><%= fo.try(:name) %></div>
  <% end %>
</div>
<div class='col-md-12'>
  <h4> Como se enteró (otro): </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.find_out_other %>
</div>
<div class='col-md-12'>
  <h4> Financiamiento: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.financing.try(:name) %>
</div>
<% if !@postulation.no_continuation.nil? %>
<div class='col-md-12'>
  <h4> ¿Continúa con la postulación?: </h4>
</div>
<div class='col-md-12'>
  <%= @postulation.no_continuation ? "Si" : "No" %>
</div>
<% else %>
<div class='col-md-12'>
  <h4> ¿Continúa con la postulación?: </h4>
</div>
<div class='col-md-12'>
 No aplica
</div>
<% end %>
<!--
<%= link_to 'Edit', edit_postulation_path(@postulation) %> |
<%= link_to 'Back', postulations_path %>
-->