config/routes.rb
Rails.application.routes.draw do
  resources :postulations do
    get '/control_interno' => "postulations#control", on: :member
    get '/download_files' => "postulations#download_files", on: :member
    get '/data_dump' => "postulations#data_dump", on: :collection
  end
  resources :info_requests
  devise_for :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  as :postulations do
    get "/postular" => "postulations#new"
  end
  
  
  as :info_request do
    get "/solicitar_informacion" => "info_requests#new"
  end
  
  root "landings#index"

end

app/models/info_request.rb
class InfoRequest < ActiveRecord::Base
  belongs_to :program
  has_and_belongs_to_many :find_outs
end

app/controllers/info_requests_controller.rb
class InfoRequestsController < ApplicationController
  before_action :set_info_request, only: [:show, :edit, :update, :destroy]
  before_action :restrict_not_logged, only: [:index, :update, :destroy, :edit]
  
  # GET /info_requests
  # GET /info_requests.json
  def index
    if current_user.has_any_role? :admin, :acceso
      respond_to do |format|
        format.html
        format.json { render json: InfoRequestDatatable.new(view_context) }
      end
    else
      redirect_to :root
    end
  end

  # GET /info_requests/1
  # GET /info_requests/1.json
  def show
    render "recieved" if !current_user
  end

  # GET /info_requests/new
  def new
    @info_request = InfoRequest.new
  end

  # GET /info_requests/1/edit
  def edit
  end

  # POST /info_requests
  # POST /info_requests.json
  def create
    @info_request = InfoRequest.new(info_request_params)

    respond_to do |format|
      if @info_request.save
        format.html { redirect_to @info_request, notice: 'Solicitud de información enviada.' }
        format.json { render :show, status: :created, location: @info_request }
      else
        format.html { render :new }
        format.json { render json: @info_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /info_requests/1
  # PATCH/PUT /info_requests/1.json
  def update
    respond_to do |format|
      if @info_request.update(info_request_params)
        format.html { redirect_to @info_request, notice: 'Info request was successfully updated.' }
        format.json { render :show, status: :ok, location: @info_request }
      else
        format.html { render :edit }
        format.json { render json: @info_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /info_requests/1
  # DELETE /info_requests/1.json
  def destroy
    @info_request.destroy
    respond_to do |format|
      format.html { redirect_to info_requests_url, notice: 'Info request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def restrict_not_logged
      redirect_to root_path if !current_user
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_info_request
      @info_request = InfoRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_request_params
      params.require(:info_request).permit(:program_id, :name, :internal_commentary, :surname, :second_surname, :contact_phone, :rut, :observations, :email, :find_out_other, find_out_ids: [])
    end
end

app/helpers/info_requests_helper.rb
module InfoRequestsHelper
end

app/views/info_requests/_form.html.erb
<%= simple_form_for(@info_request) do |f| %>

  <div class="col-md-8 col-md-offset-2">
<!--    <%= f.association :program, label: "Nombre del programa" %>-->
    <%= f.association :program, :collection => Program.where(:active => true), label: "Nombre del programa" %>
    <%= f.input :name, label: "Nombre" %>
    <%= f.input :surname, label: "Apellido paterno" %>
    <%= f.input :second_surname, label: "Apellido materno" %>
    <%= f.input :contact_phone, label: "Fono de contacto" %>
    <%= f.input :rut, label: "Cédula de identidad o pasaporte" %>
    <%= f.input :email, label: "Correo electronico" %>
    <%= f.input :observations, label: "Consulta" %>
    <%= f.association :find_outs, label: "¿Como se enteró del programa?", input_html: {multiple: true, class: 'chosen-select', 'data-placeholder': '¿Como te enteraste?, click aquí'} %>
    <%= f.input :find_out_other, label: "Especifique donde se enteró.", wrapper_html: { class: 'find_out_wrapper' } %>
  </div>

  <div class='col-md-12'>&nbsp;</div>
  <div class="col-md-5 col-md-offset-5">
    <%= f.button :submit, "Solicitar información" %>
  </div>
<% end %>

<div class="modal fade" id="modal-validation" tabindex="-1" role="dialog" aria-labelledby="modal-validation">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="exampleModalLabel">Error de validación</h4>
        </div>
        <div class="modal-body text-center">
          <h4>Los campos en rojo son obligatorios.</h4>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>

app/views/info_requests/_form_internal_commentary.html.erb
<%= simple_form_for(@info_request) do |f| %>
  <%= f.error_notification %>

  <div class="col-md-8 col-md-offset-2">
    <%= f.input :internal_commentary, label: "Observacion Interna" %>
  </div>
  <div class='col-md-12'>
    <%= f.button :submit, "Modificar Observación Interna", class: "btn btn-info col-md-6 col-md-offset-3" %>
  </div>
<% end %>

app/views/info_requests/edit.html.erb
<%= render 'form_internal_commentary' %>

<%= link_to 'Back', info_requests_path %>

app/views/info_requests/index.html.erb
<div class='col-md-12 col-sm-12'>
  <h1>Solicitudes de información</h1>
  <table class='table' id="info-request-table" data-source="<%= info_requests_path(format: :json) %>">
    <thead>
      <tr>
        <th>Programa</th>
        <th>Nombre</th>
        <th>Email</th>
        <th>Rut</th>
        <th>Comentarios</th>
        <th>Como se entero</th>
        <th>Obs. Interna</th>
        <% if current_user.has_role? :admin %>
        <th>Opciones</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

<!--<%= link_to 'New Info request', new_info_request_path %>-->

app/views/info_requests/new.html.erb
<div class='col-md-12 spacer50'>&nbsp;</div>
<div class='col-md-12 text-center'>
  <h1 class='titulo1'>Solicitud de información</h1>
</div>
<br />
<%= render 'form' %>

<!--<%= link_to 'Back', info_requests_path %>-->

app/views/info_requests/recieved.html.erb
<div class='spacer50'>&nbsp;</div>
<div class='spacer50'>&nbsp;</div>
<div class='col-md-12'>
  <h4>Estimado/a :</h4>
  <div class='spacer25'>&nbsp;</div>
  <h4>Su solicitud ha sido recibida por la Escuela de Posgrado.</h4>
  <div class='spacer25'>&nbsp;</div>
  <h4>Le saluda atentamente,</h4>
  <div class='spacer25'>&nbsp;</div>
  <h4>Escuela de Posgrado</h4>
  <h4>Facultad de Artes</h4>
  <h4>Universidad de Chile</h4>
</div>

app/views/info_requests/show.html.erb
<div class='col-md-12'>
  <h4> Programa: </h4>
</div>
<div class='col-md-12'>
  <%= @info_request.program.try(:name) %>
</div>

<div class='col-md-12'>
  <h4> Nombre: </h4>
</div>
<div class='col-md-12'>
  <%= "#{@info_request.name} #{@info_request.surname} #{@info_request.second_surname}" %>
</div>

<div class='col-md-12'>
  <h4> Rut: </h4>
</div>
<div class='col-md-12'>
   <%= @info_request.rut %>
</div>

<div class='col-md-12'>
  <h4> Observaciones: </h4>
</div>
<div class='col-md-12'>
   <%= @info_request.observations %>
</div>

<div class='col-md-12'>
  <h4> Como se entero del programa: </h4>
</div>
<div class='col-md-12'>
  <% @info_request.find_outs.map do |fo| %>
  <div class='col-md-12'><%= fo.try(:name) %></div>
  <% end %>
</div>
<div class='col-md-12'>&nbsp;</div>
<div class='col-md-12'>
  <a href='/info_requests'><button class='btn btn-default'>Volver</button></a>
</div>
<!--<%= link_to 'Edit', edit_info_request_path(@info_request) %> |-->
<!--<%= link_to 'Volver', info_requests_path %>-->